### ISSUE TITLE
crash report

### ISSUE THREAD

**Issue by Puke84** [oitsjustjose/Miscellany#2]
Another one for you. was mining gravel with a tinkers shovel. and got this crash.

http://pastebin.com/HfeNn5ct

**Comment by oitsjustjose** [comment]
Hmm. Well, that was for a dumb achievement that I was planning to remove anyways... it was more of a test to see if I understood how they worked. I'll make a few fixes and release a version 'a' on the CurseForge to hopefully resolve these bugs :)

**Comment by oitsjustjose** [comment]
Removed this silly achievement, it was causing a crash for an achievement whose purpose was dumb anyways.
